plugins=net.runelite.client.plugins.Plugin
plugin.name=My Custom Plugin
plugin.description=This is my custom .asd plugin.
plugin.version=1.0
plugin.author=asd
plugin.dependencies=none
plugin.main=net.runelite.client.plugins.asd.PluginSocketServer
